global:
  domain: tunecloud.local
  grafanaDomain: grafana.tunecloud.local
server:
  image: ghcr.io/skippingclass/tunecloud-server:sha-19b547e
  replicas: 1
client:
  image: ghcr.io/skippingclass/tunecloud-client:sha-19b547e
  replicas: 1
