global:
  domain: tunecloud.local
  grafanaDomain: grafana.tunecloud.local
server:
  image: ghcr.io/skippingclass/tunecloud-server:sha-a284436
  replicas: 1
client:
  image: ghcr.io/skippingclass/tunecloud-client:sha-a284436
  replicas: 1
