global:
  domain: tunecloud.local
  grafanaDomain: grafana.tunecloud.local
server:
  image: ghcr.io/skippingclass/tunecloud-server:sha-e08222a
  replicas: 1
client:
  image: ghcr.io/skippingclass/tunecloud-client:sha-e08222a
  replicas: 1
